name: release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**'  # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:

    runs-on: windows-2019

    env:
        projName: V2RayGCon
        projCfg: Release
        releaseNoteUrl: "https://vrnobody.github.io/V2RayGCon/04-dev/01-release-log/"
        verStr: '1.8.x'
        boxAppend: box
        webuiPkgName: 'webui.zip'
        webuiVer: '0.0.5.0'
        webuiUrl: 'https://github.com/vrnobody/WebUI/releases/download'
        # v2rayCorePkgName: 'v2ray-windows-64.zip'
        v2rayCorePkgName: 'Xray-windows-64.zip'
        v2rayCoreVer: 'v1.8.4'
        # https://github.com/v2ray/v2ray-core/releases/download/v4.20.0/v2ray-windows-32.zip
        # https://github.com/XTLS/Xray-core/releases/download/v1.4.0/Xray-windows-64.zip
        # v2rayCoreUrl: 'https://github.com/v2fly/v2ray-core/releases/download'
        v2rayCoreUrl: 'https://github.com/XTLS/Xray-core/releases/download'

    steps:
        - name: Checkout master
          uses: actions/checkout@v4

        - name: Show versions
          run: |
            python --version
            echo "power shell version:"
            $Host.Version

        - name: Setup .net framework env
          uses: vrnobody/Setup-DotNetFrameworkEnv@v1.10.1

        - name: Restore packages
          run: nuget restore ${env:projName}.sln

        - name: Build solution
          run: msbuild ${env:projName}.sln -p:Configuration=${env:projCfg}

        - name: Run unit tests
          run: |
            function Invoke-VSTest {
              & "vstest.console.exe" $args
              if(-not $?){ throw "fail!" }
            }
            Invoke-VSTest "V2RayGConTests\bin\${{ env.projCfg }}\V2RayGCon.Test.dll"
            Invoke-VSTest "VgcApisTests\bin\${{ env.projCfg }}\VgcApisTests.dll"
            Invoke-VSTest "Plugins\ProxySetterTests\bin\${{ env.projCfg }}\ProxySetterTests.dll"

        - name: Create V2RayGCon.zip
          shell: pwsh
          run: |
            $outdir = "${env:projName}/bin/${env:projCfg}"
            Invoke-WebRequest -Uri "${env:webuiUrl}/${env:webuiVer}/${env:webuiPkgName}" -OutFile "${env:webuiPkgName}"
            Expand-Archive "${env:webuiPkgName}" -DestinationPath "${outdir}/3rd/neolua/webui"
            Compress-Archive -Path ${outdir}/* ${env:projName}'.zip'

        - name: Upload V2RayGCon.zip
          uses: actions/upload-artifact@v3
          with:
            name: ${{ env.projName }}.zip
            path: ${{ env.projName}}/bin/${{ env.projCfg }}/*

        - name: Create V2RayGCon-box.zip
          shell: pwsh
          run: |
            $outdir = "${env:projName}/bin/${env:projCfg}"
            Invoke-WebRequest -Uri "${env:v2rayCoreUrl}/${env:v2rayCoreVer}/${env:v2rayCorePkgName}" -OutFile "${env:v2rayCorePkgName}"
            Expand-Archive "${env:v2rayCorePkgName}" -DestinationPath "${outdir}/3rd/core"
            Compress-Archive -Path ${outdir}/* ${env:projName}'-'${env:boxAppend}'.zip'

        - name: Upload V2RayGCon-box.zip
          uses: actions/upload-artifact@v3
          with:
            name: ${{ env.projName }}-${{ env.boxAppend }}.zip
            path: ${{ env.projName}}/bin/${{ env.projCfg }}/*

        - name: Calculate MD5 hash
          shell: pwsh
          run: |
            $hash1 = Get-FileHash "${env:projName}.zip" -Algorithm MD5
            $hash2 = Get-FileHash "${env:projName}-${env:boxAppend}.zip" -Algorithm MD5
            $hv1 = $hash1.Hash
            $hv2 = $hash2.Hash
            echo "hashVgcZip=${hv1}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            echo "hashVgcBoxZip=${hv2}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        - name: Publish Release
          uses: ncipollo/release-action@v1.12.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            name: 'v${{ env.verStr }}'
            tag: ${{ env.verStr }}
            body: |
              本项目支持的最高v2ray-core版本是`v4.45.2`
              [Release logs 发布记录](${{ env.releaseNoteUrl }})
              
              #### 变化：
               * 变化1
              
              #### MD5:
              ${{ env.projName }}.zip (${{ env.hashVgcZip }})
              ${{ env.projName }}-${{ env.boxAppend }}.zip (${{ env.hashVgcBoxZip }})

              #### 备注:
              WebUI v${{ env.webuiVer }}
              ${{ env.projName }}-${{ env.boxAppend }}.zip打包了Xray-core-win64 ${{ env.v2rayCoreVer }}
            draft: true
            prerelease: false
            artifacts: "${{ env.projName }}.zip,${{ env.projName }}-${{ env.boxAppend }}.zip"
